In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [5]:
URL = "https://courses.rice.edu/admweb/!SWKSCAT.cat?p_acyr_code=2023&p_action=CATASRCH&p_onebar=&p_mode=AND&p_subj_cd=&p_subj=&p_dept=&p_school=&p_df=%2B&p_submit="

In [6]:
page = requests.get(URL)

In [7]:
soup = BeautifulSoup(page.content, "html.parser")

In [8]:
table = soup.find("table", class_="table-condensed")

In [9]:
courses = table.find_all("tr")

In [14]:
skip = True
data = []
for course in courses:
    if skip:
        skip = False
        continue
    course_code = course.find("td", class_="cataCourse")
    course_code_link = course_code.find("a")["href"]
    course_code = course_code.text
    title = course.find("td", class_="cataTitle").text
    for idx, item in enumerate(course.find_all("td", class_="cataDist")):
        if idx == 0:
            dist_group = item.text
        else:
            analyzing_div = item.text
    credits = course.find("td", class_="credits").text
    data.append([
        course_code,
        course_code_link,
        title,
        dist_group,
        analyzing_div,
        credits
    ])
df = pd.DataFrame(data, columns=['Course', 'URL', 'Title', 'Distribution Group', 'Analyzing Diversity', 'Credits'])

In [15]:
df

,Course,URL,Title,Distribution Group,Analyzing Diversity,Credits
0,AAAS 200,/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr...,INTRO TO AAAS,Distribution Group I,,3
1,AAAS 300,/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr...,WRITING BLACK LIVES,Distribution Group I,,3
2,AAAS 510,/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr...,INTRO TO DIASPORIC STUDIES,,,3
3,AAAS 600,/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr...,AF & AFAM STUDIES COLLOQUIUM,,,0
4,AFSC 101,/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr...,FOUNDATION OF THE USAF I,,,2
...,...,...,...,...,...,...
5990,UNIV 502,/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr...,PRACTICUM IN COLLEGE TEACHING,,,3
5991,UNIV 555,/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr...,INTER-INSTITUTIONAL TRANSFER,,,1 TO 6
5992,UNIV 594,/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr...,RESPONSIBLE CONDUCT - RESEARCH,,,1
5993,UNIV 599,/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr...,TEACHING PORTFOLIO,,,2
5994,UNIV 677,/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr...,SPECIAL TOPICS,,,1 TO 4